Implement KMeans visualization.
packing-box/docker-packing-box pull request #29
Opened 2023-01-02 11:44 UTC by smarbal

Implemented KMeans visualization which produces a scatter plot (see [6b82502b2a78723970a6197d5389f27c4259f214](https://github.com/packing-box/experiments-unsupervised-learning/commit/6b82502b2a78723970a6197d5389f27c4259f214)). 
It isn't optimal since it will recompute features for all the data, which has already been done during the `train` phase, but I couldn't manage to do it otherwise.

This pull request also contains small fixes following packing-box/docker-packing-box#28. Some fixes still need to be done on that issue. 
The image that I had produced was using my temporary fix and didn't take last commit into account.

2023-01-02 17:29 UTC, dhondta requested changes
@smarbal You're right for the missing import but the `.source` is aimed to trigger the related property. If you set `._source`, it will only modify the protected attribute and it won't execute the logic of the property's setter.

2023-01-02 17:31 UTC, smarbal commented
@dhondta 
I'll look into it but I was having an error with L43 since it couldn't return anything. I'll provide the traceback soon.

2023-01-02 17:33 UTC, dhondta commented
@smarbal this is not the point ! I forgot to put the line for setting the protected attribute ; this should be line 49 : 
```python
        self._source = p
```

2023-01-02 17:51 UTC, smarbal commented
@dhondta 
The change has been reversed.

2023-01-02 18:07 UTC, smarbal commented
I've also added `self.source = p` on line 49 and can push the commit if you want. 
But with or without it, the following error occurs (when making a dataset) : 
```
Traceback (most recent call last):
  File "/home/user/.opt/tools/dataset", line 153, in <module>
    ds.fix()
  File "/home/user/.local/lib/python3.10/site-packages/pbox/common/utils.py", line 142, in _wrapper
    return f(s, *a, **kw)
  File "/home/user/.local/lib/python3.10/site-packages/pbox/common/dataset.py", line 344, in fix
    for exe in self:
  File "/home/user/.local/lib/python3.10/site-packages/pbox/learning/dataset.py", line 78, in __iter__
    exe = Executable(row, dataset=self)
  File "/home/user/.local/lib/python3.10/site-packages/pbox/learning/executable.py", line 15, in __new__
    Features(None)  # lazily populate Features.registry at first instantiation
  File "/home/user/.local/lib/python3.10/site-packages/tinyscript/preimports/log.py", line 91, in _wrapper
    return f(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/pbox/learning/features/__init__.py", line 67, in __init__
    with Features.source.open() as f:
  File "/home/user/.local/lib/python3.10/site-packages/pbox/learning/features/__init__.py", line 43, in source
    return self._source
AttributeError: type object 'Features' has no attribute '_source'


```

2023-01-03 17:54 UTC, dhondta approved these changes

2023-01-03 17:54 UTC, merged

2023-01-03 18:02 UTC, dhondta commented
@smarbal 
I just pointed out something : 

```python
    X = PCA(20).fit_transform(X)
    X = TSNE(n_components=2).fit_transform(X)
```

Why do you use a PCA with 20 components then a t-SNE with dimensionality 2 ? Why not directly a PCA with 2 components ?

2023-01-03 18:49 UTC, smarbal commented
@dhondta 
I was getting mixed results on my first tries with directly a PCA with 2 components or directly a t-SNE with 2 components. t-SNE is recommended because usually better than PCA, but wasn't having good performances due to the high dimensionality of the data. I've found multiple sources that therefore first use PCA as pre-processing to reduce the dimensionality and then t-SNE for visualization.

A configuration file or parameters in the visualization tool to finetune these parameters would probably be interesting.

2023-01-04 13:07 UTC, smarbal commented
@dhondta
It does seem to work as intended. 
Note that previously the result image would be saved in `/experiments`, while here it gets saved in the root directory (directly in /mnt/share).